apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Slack 通知模板
  service.slack: |
    token: $slack-token
  template.app-sync-succeeded: |
    message: |
      ✅ {{.app.metadata.name}} 同步成功
      镜像: {{range .app.status.summary.images}}{{.}}{{end}}
      Revision: {{.app.status.sync.revision}}
      时间: {{.app.status.operationState.finishedAt}}
  template.app-sync-failed: |
    message: |
      ❌ {{.app.metadata.name}} 同步失败
      错误: {{.app.status.operationState.message}}
      Revision: {{.app.status.sync.revision}}
  template.app-health-degraded: |
    message: |
      ⚠️ {{.app.metadata.name}} 健康状态异常
      Health: {{.app.status.health.status}}
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded]
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]
