apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  labels:
    app: angelpay
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /tmp/mysql-data
